openapi: "3.0.3"
info:
  title: "BPMN-PNML-Transformer"
  description: "Transforms BPMN diagrams to PNML or PNML diagrams to BPMN."
  version: "1.0.0"
servers:
  - url: "https://europe-west3-woped-422510.cloudfunctions.net"
paths:
  "/transform":
    post:
      summary: "Returns the transformed diagram as XML."
      parameters:
        - name: direction
          in: query
          required: true
          schema:
            type: string
            enum: [bpmntopnml, pnmltobpmn]
          description: Specifies the direction of the transformation.
      requestBody:
        description: "Info: Swagger only works if the XML does not contain any line breaks and all quotation marks are escaped with a backslash as shown in the examples. For other XMLs you could use tools like Bruno."
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf: 
                - properties:
                    direction:
                      type: string
                      enum: [bpmntopnml]
                    bpmn:
                      type: string
                      description: 'Necessary parameter, if direction is "bpmntopnml".'
                  required: [direction, bpmn]
                - properties:
                    direction:
                      type: string
                      enum: [pnmltobpmn]
                    pnml:
                      type: string
                      description: 'Necessary parameter, if direction is "pnmltobpmn".'
                  required: [direction, pnml]
            examples:
              bpmntopnml:
                summary: Example of a BPMN to PNML request
                value:
                  bpmn: "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <bpmn:definitions xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:bpmn=\"http://www.omg.org/spec/BPMN/20100524/MODEL\" xmlns:bpmndi=\"http://www.omg.org/spec/BPMN/20100524/DI\" xmlns:dc=\"http://www.omg.org/spec/DD/20100524/DC\" xmlns:di=\"http://www.omg.org/spec/DD/20100524/DI\" id=\"Definitions_0uh33yr\" targetNamespace=\"http://bpmn.io/schema/bpmn\" exporter=\"bpmn-js (https://demo.bpmn.io)\" exporterVersion=\"17.6.2\"><bpmn:process id=\"Process_05gf0wk\" isExecutable=\"false\"><bpmn:startEvent id=\"StartEvent_1kldrri\"><bpmn:outgoing>Flow_03wmhzd</bpmn:outgoing></bpmn:startEvent><bpmn:task id=\"Activity_16g2nsl\" name=\"Task\"><bpmn:incoming>Flow_03wmhzd</bpmn:incoming><bpmn:outgoing>Flow_06lknmg</bpmn:outgoing></bpmn:task><bpmn:sequenceFlow id=\"Flow_03wmhzd\" sourceRef=\"StartEvent_1kldrri\" targetRef=\"Activity_16g2nsl\" /><bpmn:endEvent id=\"Event_02tt0ub\"><bpmn:incoming>Flow_06lknmg</bpmn:incoming></bpmn:endEvent><bpmn:sequenceFlow id=\"Flow_06lknmg\" sourceRef=\"Activity_16g2nsl\" targetRef=\"Event_02tt0ub\" /></bpmn:process><bpmndi:BPMNDiagram id=\"BPMNDiagram_1\"><bpmndi:BPMNPlane id=\"BPMNPlane_1\" bpmnElement=\"Process_03gf0wk\"><bpmndi:BPMNShape id=\"_BPMNShape_StartEvent_2\" bpmnElement=\"StartEvent_1kldrri\"><dc:Bounds x=\"156\" y=\"82\" width=\"36\" height=\"36\" /></bpmndi:BPMNShape><bpmndi:BPMNShape id=\"Activity_16g2nsl_di\" bpmnElement=\"Activity_16g2nsl\"><dc:Bounds x=\"250\" y=\"60\" width=\"100\" height=\"80\" /><bpmndi:BPMNLabel /></bpmndi:BPMNShape><bpmndi:BPMNShape id=\"Event_02tt0ub_di\" bpmnElement=\"Event_02tt0ub\"><dc:Bounds x=\"412\" y=\"82\" width=\"36\" height=\"36\" /></bpmndi:BPMNShape><bpmndi:BPMNEdge id=\"Flow_03wmhzd_di\" bpmnElement=\"Flow_03wmhzd\"><di:waypoint x=\"192\" y=\"100\" /><di:waypoint x=\"250\" y=\"100\" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id=\"Flow_06lknmg_di\" bpmnElement=\"Flow_06lknmg\"><di:waypoint x=\"350\" y=\"100\" /><di:waypoint x=\"412\" y=\"100\" /></bpmndi:BPMNEdge></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></bpmn:definitions>"
              pnmltobpmn:
                summary: Example of a PNML to BPMN request
                value:
                  pnml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><pnml id=\"\"><net id=\"Process_05gf0wk\"><place id=\"Event_02tt0ub\" /><place id=\"StartEvent_1kldrri\" /><transition id=\"Activity_16g2nsl\"><name id=\"\"><graphics id=\"\"><offset id=\"\" x=\"20.0\" y=\"20.0\" /></graphics><text>Task</text></name></transition><arc id=\"Activity_16g2nslTOEvent_02tt0ub\" source=\"Activity_16g2nsl\" target=\"Event_02tt0ub\" /><arc id=\"StartEvent_1kldrriTOActivity_16g2nsl\" source=\"StartEvent_1kldrri\" target=\"Activity_16g2nsl\" /></net></pnml>"
      responses:
        200:
          description: Successful Transformation
        400:
          description: Bad Request
        404:
          description: Not Found
        408:
          description: Request Timeout after 60s
        413:
          description: Payload too large (max. 10 MB)
        429:
          description: Too Many Requests, service is temporarily unavailable.
  "/health":
    get:
      summary: Shows the health status of transformer.
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        408:
          description: Request Timeout after 60s
        429:
          description: Too Many Requests, service is temporarily unavailable.